name: 'Install iOS Provisioning Profile'
description: 'This action can install ios provisioning profile on build server'
author: 'Diet Doctor'
inputs:
  profile-base64:
    description: 'Provisioning profile provided in base64'
    required: true
runs:
  using: 'node16'
  main: 'dist/task/index.js'
  post: 'dist/post-task/index.js'
  post-if: 'success()'
