name: "tagged-release"

# on:
#   push:
#     tags:
#       - "v*"
on: [push]

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: | 
          yarn ci
          yarn build
      - run: |
          mkdir artifacts
          mv package.json artifacts
          mv action.yml artifacts
          mv lib artifacts
          mv tsconfig.json artifacts
          mv LICENSE artifacts
          mv node_modules artifacts
      - uses: actions/upload-artifact@1.0.0
        with:
          name: artifacts
          path: artifacts