name: "tagged-release"

# on:
#   push:
#     tags:
#       - "v*"
on: [push]

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn ci
      - run: yarn build
      - uses: technote-space/release-github-actions@v6
